[webservers]
localhost  ansible_connection=local

[dbservers]
localhost  ansible_connection=local

[redis]
localhost  ansible_connection=local

[tools]
localhost  ansible_connection=local

[all:vars]
target_stage=development
